//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestfulCalculator.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisor cannot be zero.
        /// </summary>
        public static string DividByZero {
            get {
                return ResourceManager.GetString("DividByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the request parameters &apos;{0}&apos;.
        /// </summary>
        public static string ErrorInRequestParameters {
            get {
                return ResourceManager.GetString("ErrorInRequestParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with the same end point name already exists &apos;{0}&apos;..
        /// </summary>
        public static string ServiceWIthTheSameEndPointNameAlreadyExists {
            get {
                return ResourceManager.GetString("ServiceWIthTheSameEndPointNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with the same route pattern already exists &apos;{0}&apos;..
        /// </summary>
        public static string ServiceWIthTheSameRoutePatternAlreadyExists {
            get {
                return ResourceManager.GetString("ServiceWIthTheSameRoutePatternAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction result is less than decimal.MinValue.
        /// </summary>
        public static string SubtractionResultLessThanMinValue {
            get {
                return ResourceManager.GetString("SubtractionResultLessThanMinValue", resourceCulture);
            }
        }
    }
}
